[package]
name = "k_means"
version = "0.1.0"
authors = ["chrism"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotlib = { git = "https://github.com/quietlychris/plotlib", branch = "master" }
rand = "0.7.2"
